/**
 * What people actually type into a shared Israeli shopping list, and the aisle
 * each one belongs in.
 *
 * This is the yardstick for guessCategory. Written as typed, not as a
 * dictionary would spell it: plurals, construct forms ("עגבניות שרי", "חזה עוף"),
 * brands ("במבה", "פמפרס"), both kinds of apostrophe ("צ'יפס" / "צ׳יפס"), double
 * and single yod, quantities in the name ("2 ק"ג עגבניות"), and English.
 *
 * `null` means "no guess is the right answer" — these keep the matcher from
 * getting so eager that it files a birthday card under dairy.
 *
 * Deliberately heavy on words that START with ב ה ו כ ל מ ש: those are the
 * letters Hebrew glues onto nouns as prefixes, and the engine used to strip one
 * off every word that began with them — which is how "בננה" became "ננה" and
 * matched nothing.
 */

export const CORPUS = [
  // ── produce ─────────────────────────────────────────────────────────────
  ['בננה', 'produce'],
  ['בננות', 'produce'],
  ['בננב', 'produce'], // a real typo from the live database
  ['עגבניה', 'produce'],
  ['עגבנייה', 'produce'],
  ['עגבניות', 'produce'],
  ['עגבניות שרי', 'produce'],
  ['2 ק"ג עגבניות', 'produce'],
  ['מלפפון', 'produce'],
  ['מלפפונים', 'produce'],
  ['חסה', 'produce'],
  ['חסה ערבית', 'produce'],
  ['גזר', 'produce'],
  ['בצל', 'produce'],
  ['בצל סגול', 'produce'],
  ['בצל ירוק', 'produce'],
  ['שום', 'produce'],
  ['פלפל אדום', 'produce'],
  ['גמבה', 'produce'],
  ['קישואים', 'produce'],
  ['חציל', 'produce'],
  ['חצילים', 'produce'],
  ['בטטה', 'produce'],
  ['בטטות', 'produce'],
  ['תפוחי אדמה', 'produce'],
  ['תפו"א', 'produce'],
  ['ברוקולי', 'produce'],
  ['כרובית', 'produce'],
  ['כרוב אדום', 'produce'],
  ['תרד', 'produce'],
  ['סלרי', 'produce'],
  ['סלק', 'produce'],
  ['צנונית', 'produce'],
  ['דלעת', 'produce'],
  ['במיה', 'produce'],
  ['פטריות', 'produce'],
  ['שמפיניון', 'produce'],
  ['פורטובלו', 'produce'],
  ["ג'ינג'ר", 'produce'],
  ['כרישה', 'produce'],
  ['שמיר', 'produce'],
  ['פטרוזיליה', 'produce'],
  ['כוסברה', 'produce'],
  ['נענע', 'produce'],
  ['בזיליקום', 'produce'],
  ['רוקט', 'produce'],
  ['ארוגולה', 'produce'],
  ['נבטים', 'produce'],
  ['לימון', 'produce'],
  ['לימונים', 'produce'],
  ['ליים', 'produce'],
  ['תפוח', 'produce'],
  ['תפוחים', 'produce'],
  ['תפוחים ירוקים', 'produce'],
  ['תפוזים', 'produce'],
  ['קלמנטינות', 'produce'],
  ['מנדרינה', 'produce'],
  ['אשכוליות', 'produce'],
  ['אבוקדו', 'produce'],
  ['תותים', 'produce'],
  ['ענבים', 'produce'],
  ['אבטיח', 'produce'],
  ['מלון', 'produce'],
  ['אפרסקים', 'produce'],
  ['נקטרינות', 'produce'],
  ['שזיפים', 'produce'],
  ['אגסים', 'produce'],
  ['רימונים', 'produce'],
  ['מנגו', 'produce'],
  ['קיווי', 'produce'],
  ['אננס', 'produce'],
  ['תמרים', 'produce'],
  ['תאנים', 'produce'],
  ['משמשים', 'produce'],
  ['דובדבנים', 'produce'],
  ["ליצ'י", 'produce'],
  ['אפרסמון', 'produce'],
  ['אוכמניות', 'produce'],
  ['פטל', 'produce'],
  ['פפאיה', 'produce'],
  ['גויאבה', 'produce'],
  ['ירקות', 'produce'],
  ['פירות', 'produce'],
  ['קלחי תירס', 'produce'],
  ['bananas', 'produce'],
  ['tomatoes', 'produce'],
  ['cucumbers', 'produce'],
  ['avocado', 'produce'],
  ['lemons', 'produce'],
  ['strawberries', 'produce'],
  ['blueberries', 'produce'],
  ['grapes', 'produce'],
  ['onions', 'produce'],
  ['potatoes', 'produce'],
  ['sweet potatoes', 'produce'],
  ['apples', 'produce'],
  ['mushrooms', 'produce'],
  ['spinach', 'produce'],
  ['carrots', 'produce'],
  ['garlic', 'produce'],
  ['ginger', 'produce'],
  ['cherry tomatoes', 'produce'],
  ['bell pepper', 'produce'],

  // ── bakery ──────────────────────────────────────────────────────────────
  ['לחם', 'bakery'],
  ['לחם אחיד', 'bakery'],
  ['לחם אחיד פרוס', 'bakery'],
  ['לחם מלא', 'bakery'],
  ['לחם שיפון', 'bakery'],
  ['לחם מחמצת', 'bakery'],
  ['לחמניות', 'bakery'],
  ['לחמניה', 'bakery'],
  ['פיתות', 'bakery'],
  ['פיתה', 'bakery'],
  ['חלה', 'bakery'],
  ['חלות', 'bakery'],
  ['באגט', 'bakery'],
  ['בגט', 'bakery'],
  ['קרואסון', 'bakery'],
  ['קרואסונים', 'bakery'],
  ['רוגלך', 'bakery'],
  ['בורקס', 'bakery'],
  ['לאפה', 'bakery'],
  ['לאפות', 'bakery'],
  ['טורטיות', 'bakery'],
  ['בייגל', 'bakery'],
  ["פוקאצ'ה", 'bakery'],
  ['עוגה', 'bakery'],
  ['עוגת שוקולד', 'bakery'],
  ['מאפינס', 'bakery'],
  ['סופגניות', 'bakery'],
  ['מצות', 'bakery'],
  ['bread', 'bakery'],
  ['pita', 'bakery'],
  ['bagels', 'bakery'],
  ['croissants', 'bakery'],
  ['tortillas', 'bakery'],
  ['challah', 'bakery'],

  // ── dairy & eggs ────────────────────────────────────────────────────────
  ['חלב', 'dairy_eggs'],
  ['חלב 3%', 'dairy_eggs'],
  ['חלב תנובה 3% בקרטון', 'dairy_eggs'],
  ['חלב סויה', 'dairy_eggs'],
  ['חלב שקדים', 'dairy_eggs'],
  ['חלב שיבולת שועל', 'dairy_eggs'],
  ['שוקו', 'dairy_eggs'],
  ['גבינה צהובה', 'dairy_eggs'],
  ['גבינה לבנה', 'dairy_eggs'],
  ['גבינת שמנת', 'dairy_eggs'],
  ['גבינות', 'dairy_eggs'],
  ["קוטג'", 'dairy_eggs'],
  ['קוטג׳ 5%', 'dairy_eggs'],
  ['בולגרית', 'dairy_eggs'],
  ['פטה', 'dairy_eggs'],
  ['מוצרלה', 'dairy_eggs'],
  ['ריקוטה', 'dairy_eggs'],
  ['מסקרפונה', 'dairy_eggs'],
  ['פרמזן', 'dairy_eggs'],
  ['צפתית', 'dairy_eggs'],
  ['לאבנה', 'dairy_eggs'],
  ['יוגורט', 'dairy_eggs'],
  ['יוגורטים', 'dairy_eggs'],
  ['יוגורט יווני', 'dairy_eggs'],
  ['אקטיביה', 'dairy_eggs'],
  ['דנונה', 'dairy_eggs'],
  ['מילקי', 'dairy_eggs'],
  ['גמדים', 'dairy_eggs'],
  ['פודינג', 'dairy_eggs'],
  ['מעדנים', 'dairy_eggs'],
  ['שמנת מתוקה', 'dairy_eggs'],
  ['שמנת חמוצה', 'dairy_eggs'],
  ['שמנת לבישול', 'dairy_eggs'],
  ['חמאה', 'dairy_eggs'],
  ['מרגרינה', 'dairy_eggs'],
  ['ביצים', 'dairy_eggs'],
  ['ביצים L', 'dairy_eggs'],
  ['ביצה', 'dairy_eggs'],
  ['קצפת', 'dairy_eggs'],
  ['טופו', 'dairy_eggs'],
  ['קפיר', 'dairy_eggs'],
  ['לבן', 'dairy_eggs'],
  ['milk', 'dairy_eggs'],
  ['eggs', 'dairy_eggs'],
  ['cheese', 'dairy_eggs'],
  ['cream cheese', 'dairy_eggs'],
  ['sour cream', 'dairy_eggs'],
  ['butter', 'dairy_eggs'],
  ['greek yogurt', 'dairy_eggs'],
  ['cottage cheese', 'dairy_eggs'],
  ['chocolate milk', 'dairy_eggs'],

  // ── meat & fish ─────────────────────────────────────────────────────────
  ['חזה עוף', 'meat_fish'],
  ['עוף שלם', 'meat_fish'],
  ['שוקיים', 'meat_fish'],
  ['שוק עוף', 'meat_fish'],
  ['כנפיים', 'meat_fish'],
  ['כנפי עוף', 'meat_fish'],
  ['פרגיות', 'meat_fish'],
  ['שניצל', 'meat_fish'],
  ['שניצלים', 'meat_fish'],
  ['עוף טחון', 'meat_fish'],
  ['בשר טחון', 'meat_fish'],
  ['בשר בקר', 'meat_fish'],
  ['אנטריקוט', 'meat_fish'],
  ['סינטה', 'meat_fish'],
  ['צלעות', 'meat_fish'],
  ['אסאדו', 'meat_fish'],
  ['שייטל', 'meat_fish'],
  ['צלי כתף', 'meat_fish'],
  ['המבורגרים', 'meat_fish'],
  ['קבב', 'meat_fish'],
  ['קציצות', 'meat_fish'],
  ['נקניקיות', 'meat_fish'],
  ['נקניק', 'meat_fish'],
  ['פסטרמה', 'meat_fish'],
  ['סלמי', 'meat_fish'],
  ['קבנוס', 'meat_fish'],
  ['הודו', 'meat_fish'],
  ['חזה הודו', 'meat_fish'],
  ['כבד עוף', 'meat_fish'],
  ['לבבות', 'meat_fish'],
  ['קורקבנים', 'meat_fish'],
  ['סלמון', 'meat_fish'],
  ['פילה סלמון', 'meat_fish'],
  ['אמנון', 'meat_fish'],
  ['דניס', 'meat_fish'],
  ['לברק', 'meat_fish'],
  ['בורי', 'meat_fish'],
  ['בקלה', 'meat_fish'],
  ['שרימפס', 'meat_fish'],
  ['קלמרי', 'meat_fish'],
  ['דגים', 'meat_fish'],
  ['מרגז', 'meat_fish'],
  ['כבש', 'meat_fish'],
  ['chicken breast', 'meat_fish'],
  ['ground beef', 'meat_fish'],
  ['salmon fillet', 'meat_fish'],
  ['sausages', 'meat_fish'],
  ['steak', 'meat_fish'],
  ['turkey breast', 'meat_fish'],
  ['shrimp', 'meat_fish'],

  // ── pantry ──────────────────────────────────────────────────────────────
  ['אורז', 'pantry'],
  ['אורז בסמטי', 'pantry'],
  ['פסטה', 'pantry'],
  ['ספגטי', 'pantry'],
  ['פנה', 'pantry'],
  ['פתיתים', 'pantry'],
  ['קוסקוס', 'pantry'],
  ['בורגול', 'pantry'],
  ['קינואה', 'pantry'],
  ['עדשים', 'pantry'],
  ['עדשים כתומות', 'pantry'],
  ['חומוס', 'pantry'],
  ['גרגרי חומוס', 'pantry'],
  ['שעועית לבנה', 'pantry'],
  ['קמח', 'pantry'],
  ['קמח תופח', 'pantry'],
  ['קמח כוסמין', 'pantry'],
  ['קמח מצה', 'pantry'],
  ['סוכר', 'pantry'],
  ['סוכר חום', 'pantry'],
  ['מלח', 'pantry'],
  ['פלפל שחור', 'pantry'],
  ['שמן', 'pantry'],
  ['שמן זית', 'pantry'],
  ['שמן זית כתית מעולה', 'pantry'],
  ['שמן קנולה', 'pantry'],
  ['חומץ', 'pantry'],
  ['חומץ בלסמי', 'pantry'],
  ['קטשופ', 'pantry'],
  ['מיונז', 'pantry'],
  ['חרדל', 'pantry'],
  ['טחינה', 'pantry'],
  ['טחינה גולמית', 'pantry'],
  ['רוטב סויה', 'pantry'],
  ['רסק עגבניות', 'pantry'],
  ['עגבניות מרוסקות', 'pantry'],
  ['שימורי עגבניות', 'pantry'],
  ['טונה', 'pantry'],
  ['קופסת טונה', 'pantry'],
  ['תירס', 'pantry'],
  ['זיתים', 'pantry'],
  ['מלפפונים חמוצים', 'pantry'],
  ['חמוצים', 'pantry'],
  ['שימורים', 'pantry'],
  ['ריבה', 'pantry'],
  ['דבש', 'pantry'],
  ['סילאן', 'pantry'],
  ['נוטלה', 'pantry'],
  ['ממרח שוקולד', 'pantry'],
  ['חמאת בוטנים', 'pantry'],
  ['חלבה', 'pantry'],
  ['קפה', 'pantry'],
  ['נס קפה', 'pantry'],
  ['קפסולות קפה', 'pantry'],
  ['קפה טורקי', 'pantry'],
  ['תה', 'pantry'],
  ['תה ירוק', 'pantry'],
  ['קורנפלקס', 'pantry'],
  ['דגני בוקר', 'pantry'],
  ['גרנולה', 'pantry'],
  ['שיבולת שועל', 'pantry'],
  ['פפריקה', 'pantry'],
  ['כמון', 'pantry'],
  ['כורכום', 'pantry'],
  ['קינמון', 'pantry'],
  ['זעתר', 'pantry'],
  ['אורגנו', 'pantry'],
  ['שקדים', 'pantry'],
  ['אגוזי מלך', 'pantry'],
  ['צימוקים', 'pantry'],
  ['שקדי מרק', 'pantry'],
  ['אבקת מרק', 'pantry'],
  ['אטריות', 'pantry'],
  ['לזניה', 'pantry'],
  ['מקרוני', 'pantry'],
  ['קורנפלור', 'pantry'],
  ['אבקת אפייה', 'pantry'],
  ['סודה לשתייה', 'pantry'],
  ['שמרים', 'pantry'],
  ['תמצית וניל', 'pantry'],
  ['סוכר וניל', 'pantry'],
  ['קקאו', 'pantry'],
  ['פירורי לחם', 'pantry'],
  ['קרוטונים', 'pantry'],
  ['חלב קוקוס', 'pantry'],
  ['קוקוס טחון', 'pantry'],
  ['rice', 'pantry'],
  ['pasta', 'pantry'],
  ['olive oil', 'pantry'],
  ['flour', 'pantry'],
  ['sugar', 'pantry'],
  ['ketchup', 'pantry'],
  ['tuna', 'pantry'],
  ['canned corn', 'pantry'],
  ['peanut butter', 'pantry'],
  ['cereal', 'pantry'],
  ['oats', 'pantry'],
  ['coffee', 'pantry'],
  ['honey', 'pantry'],
  ['hummus', 'pantry'],
  ['lentils', 'pantry'],
  ['chickpeas', 'pantry'],

  // ── frozen ──────────────────────────────────────────────────────────────
  ['גלידה', 'frozen'],
  ['גלידות', 'frozen'],
  ['גלידת וניל', 'frozen'],
  ['ארטיקים', 'frozen'],
  ['קרטיבים', 'frozen'],
  ['שלגונים', 'frozen'],
  ['מלאווח', 'frozen'],
  ["ג'חנון", 'frozen'],
  ['ג׳חנון', 'frozen'],
  ['פיצה', 'frozen'],
  ['פיצה קפואה', 'frozen'],
  ['ירקות קפואים', 'frozen'],
  ['אפונה קפואה', 'frozen'],
  ['ברוקולי קפוא', 'frozen'],
  ['שעועית ירוקה קפואה', 'frozen'],
  ['שניצל קפוא', 'frozen'],
  ["צ'יפס קפוא", 'frozen'],
  ['בורקס קפוא', 'frozen'],
  ['בצק עלים', 'frozen'],
  ['קוביות קרח', 'frozen'],
  ['אדממה', 'frozen'],
  ['תות קפוא', 'frozen'],
  ['פירות קפואים', 'frozen'],
  ['סורבה', 'frozen'],
  ['frozen pizza', 'frozen'],
  ['ice cream', 'frozen'],
  ['frozen peas', 'frozen'],
  ['popsicles', 'frozen'],

  // ── snacks & sweets ─────────────────────────────────────────────────────
  ['במבה', 'snacks_sweets'],
  ['ביסלי', 'snacks_sweets'],
  ['דוריטוס', 'snacks_sweets'],
  ["צ'יטוס", 'snacks_sweets'],
  ['אפרופו', 'snacks_sweets'],
  ["תפוצ'יפס", 'snacks_sweets'],
  ['פרינגלס', 'snacks_sweets'],
  ['חטיפים', 'snacks_sweets'],
  ['חטיף אנרגיה', 'snacks_sweets'],
  ['חטיף חלבון', 'snacks_sweets'],
  ['חטיף אורז', 'snacks_sweets'],
  ['שוקולד', 'snacks_sweets'],
  ['שוקולד חלב', 'snacks_sweets'],
  ['קינדר', 'snacks_sweets'],
  ['מילקה', 'snacks_sweets'],
  ['סניקרס', 'snacks_sweets'],
  ['קליק', 'snacks_sweets'],
  ['פסק זמן', 'snacks_sweets'],
  ['מקופלת', 'snacks_sweets'],
  ['כיף כף', 'snacks_sweets'],
  ['עוגיות', 'snacks_sweets'],
  ["עוגיות שוקולד צ'יפס", 'snacks_sweets'],
  ['ופלים', 'snacks_sweets'],
  ['וופל', 'snacks_sweets'],
  ['סוכריות', 'snacks_sweets'],
  ['סוכריות גומי', 'snacks_sweets'],
  ['מסטיק', 'snacks_sweets'],
  ['מרשמלו', 'snacks_sweets'],
  ['פופקורן', 'snacks_sweets'],
  ['בייגלה', 'snacks_sweets'],
  ['פיצוחים', 'snacks_sweets'],
  ['גרעינים', 'snacks_sweets'],
  ['בוטנים', 'snacks_sweets'],
  ['פיסטוקים', 'snacks_sweets'],
  ['קרקרים', 'snacks_sweets'],
  ['פתי בר', 'snacks_sweets'],
  ['chips', 'snacks_sweets'],
  ['chocolate', 'snacks_sweets'],
  ['cookies', 'snacks_sweets'],
  ['candy', 'snacks_sweets'],
  ['popcorn', 'snacks_sweets'],
  ['pretzels', 'snacks_sweets'],

  // ── beverages ───────────────────────────────────────────────────────────
  ['מים', 'beverages'],
  ['מים מינרלים', 'beverages'],
  ['שישיית מים', 'beverages'],
  ['מים מוגזים', 'beverages'],
  ['סודה', 'beverages'],
  ['קולה', 'beverages'],
  ['קוקה קולה', 'beverages'],
  ['קוקה קולה זירו', 'beverages'],
  ['פפסי', 'beverages'],
  ['ספרייט', 'beverages'],
  ['פאנטה', 'beverages'],
  ['שוופס', 'beverages'],
  ['מיץ תפוזים', 'beverages'],
  ['מיץ ענבים', 'beverages'],
  ['מיץ לימון', 'beverages'],
  ['פריגת', 'beverages'],
  ['פרימור', 'beverages'],
  ['ספרינג', 'beverages'],
  ['נביעות', 'beverages'],
  ['עין גדי', 'beverages'],
  ['מי עדן', 'beverages'],
  ['נסטי', 'beverages'],
  ['תה קר', 'beverages'],
  ['איס טי', 'beverages'],
  ['לימונדה', 'beverages'],
  ['משקה אנרגיה', 'beverages'],
  ['רד בול', 'beverages'],
  ['קפה קר', 'beverages'],
  ['תרכיז', 'beverages'],
  ['סירופ פטל', 'beverages'],
  ['water', 'beverages'],
  ['sparkling water', 'beverages'],
  ['coke', 'beverages'],
  ['orange juice', 'beverages'],
  ['lemonade', 'beverages'],
  ['iced tea', 'beverages'],
  ['energy drink', 'beverages'],

  // ── alcohol ─────────────────────────────────────────────────────────────
  ['בירה', 'alcohol'],
  ['בירות', 'alcohol'],
  ['שישיית בירה', 'alcohol'],
  ['יין', 'alcohol'],
  ['יין אדום', 'alcohol'],
  ['יין לבן', 'alcohol'],
  ['ערק', 'alcohol'],
  ['וודקה', 'alcohol'],
  ['ויסקי', 'alcohol'],
  ["ג'ין", 'alcohol'],
  ['טקילה', 'alcohol'],
  ['ליקר', 'alcohol'],
  ['קאווה', 'alcohol'],
  ['שמפניה', 'alcohol'],
  ['למברוסקו', 'alcohol'],
  ['גולדסטאר', 'alcohol'],
  ['קרלסברג', 'alcohol'],
  ['טובורג', 'alcohol'],
  ['הייניקן', 'alcohol'],
  ['קורונה', 'alcohol'],
  ['beer', 'alcohol'],
  ['red wine', 'alcohol'],
  ['vodka', 'alcohol'],
  ['whiskey', 'alcohol'],

  // ── baby ────────────────────────────────────────────────────────────────
  ['חיתולים', 'baby'],
  ['טיטולים', 'baby'],
  ['האגיס', 'baby'],
  ['פמפרס', 'baby'],
  ['מגבונים', 'baby'],
  ['מגבונים לחים', 'baby'],
  ['מטרנה', 'baby'],
  ['סימילאק', 'baby'],
  ['נוטרילון', 'baby'],
  ['תמ"ל', 'baby'],
  ['מחית', 'baby'],
  ['מחית פירות', 'baby'],
  ['דייסה', 'baby'],
  ['דייסת תינוקות', 'baby'],
  ['מוצץ', 'baby'],
  ['מוצצים', 'baby'],
  ['בקבוק לתינוק', 'baby'],
  ['קרם החתלה', 'baby'],
  ['משחת החתלה', 'baby'],
  ['שמפו לתינוקות', 'baby'],
  ['diapers', 'baby'],
  ['baby wipes', 'baby'],
  ['formula', 'baby'],

  // ── household ───────────────────────────────────────────────────────────
  ['אקונומיקה', 'household'],
  ['סנו', 'household'],
  ["סנו ג'אוול", 'household'],
  ['כלור', 'household'],
  ['נוזל כלים', 'household'],
  ['סבון כלים', 'household'],
  ['פיירי', 'household'],
  ['טבליות למדיח', 'household'],
  ['מלח למדיח', 'household'],
  ['אבקת כביסה', 'household'],
  ["ג'ל כביסה", 'household'],
  ['מרכך כביסה', 'household'],
  ['מסיר כתמים', 'household'],
  ['מסיר שומנים', 'household'],
  ['מסיר אבנית', 'household'],
  ['נוזל רצפות', 'household'],
  ['נייר טואלט', 'household'],
  ['נייר טואלט 32 גלילים', 'household'],
  ['מגבות נייר', 'household'],
  ['טישו', 'household'],
  ['ממחטות', 'household'],
  ['שקיות אשפה', 'household'],
  ['שקיות זבל', 'household'],
  ['שקיות הקפאה', 'household'],
  ['ניילון נצמד', 'household'],
  ['נייר כסף', 'household'],
  ['נייר אפייה', 'household'],
  ['ספוגים', 'household'],
  ['צמר פלדה', 'household'],
  ['מטליות', 'household'],
  ['סמרטוט', 'household'],
  ['כפפות', 'household'],
  ['סוללות', 'household'],
  ['נורות', 'household'],
  ['גפרורים', 'household'],
  ['נרות שבת', 'household'],
  ['מטהר אוויר', 'household'],
  ['ספריי נגד יתושים', 'household'],
  ['מגבוני ניקוי', 'household'],
  ['laundry detergent', 'household'],
  ['toilet paper', 'household'],
  ['paper towels', 'household'],
  ['garbage bags', 'household'],
  ['dish soap', 'household'],
  ['bleach', 'household'],
  ['sponges', 'household'],
  ['aluminum foil', 'household'],
  ['batteries', 'household'],

  // ── disposables ─────────────────────────────────────────────────────────
  ['צלחות חד פעמיות', 'disposables'],
  ['צלחות', 'disposables'],
  ['כוסות חד-פעמיות', 'disposables'],
  ['כוסות', 'disposables'],
  ['סכו"ם חד פעמי', 'disposables'],
  ['מזלגות', 'disposables'],
  ['כפות', 'disposables'],
  ['כפיות', 'disposables'],
  ['מפיות', 'disposables'],
  ['קשיות', 'disposables'],
  ['מגשים', 'disposables'],
  ['תבניות אלומיניום', 'disposables'],
  ['שיפודים', 'disposables'],
  ['קיסמים', 'disposables'],
  ['מפה חד פעמית', 'disposables'],
  ['disposable cups', 'disposables'],
  ['paper plates', 'disposables'],
  ['napkins', 'disposables'],
  ['straws', 'disposables'],

  // ── personal care ───────────────────────────────────────────────────────
  ['שמפו', 'personal_care'],
  ['מרכך שיער', 'personal_care'],
  ['סבון', 'personal_care'],
  ['סבון ידיים', 'personal_care'],
  ['סבון גוף', 'personal_care'],
  ["ג'ל רחצה", 'personal_care'],
  ['תחליב רחצה', 'personal_care'],
  ['משחת שיניים', 'personal_care'],
  ['מברשת שיניים', 'personal_care'],
  ['מברשות שיניים', 'personal_care'],
  ['מי פה', 'personal_care'],
  ['חוט דנטלי', 'personal_care'],
  ['דאודורנט', 'personal_care'],
  ['תחבושות', 'personal_care'],
  ['טמפונים', 'personal_care'],
  ['פדים', 'personal_care'],
  ['קרם ידיים', 'personal_care'],
  ['קרם לחות', 'personal_care'],
  ['קרם הגנה', 'personal_care'],
  ['קרם פנים', 'personal_care'],
  ['סכיני גילוח', 'personal_care'],
  ['קצף גילוח', 'personal_care'],
  ['אפטרשייב', 'personal_care'],
  ['בושם', 'personal_care'],
  ['מסיר לק', 'personal_care'],
  ['צמר גפן', 'personal_care'],
  ['מקלונים', 'personal_care'],
  ['אקמול', 'personal_care'],
  ['נורופן', 'personal_care'],
  ['אדוויל', 'personal_care'],
  ['אופטלגין', 'personal_care'],
  ['ויטמין D', 'personal_care'],
  ['ויטמינים', 'personal_care'],
  ['אומגה 3', 'personal_care'],
  ['פלסטרים', 'personal_care'],
  ['עדשות מגע', 'personal_care'],
  ['ספריי לשיער', 'personal_care'],
  ['צבע לשיער', 'personal_care'],
  ['shampoo', 'personal_care'],
  ['toothpaste', 'personal_care'],
  ['toothbrush', 'personal_care'],
  ['deodorant', 'personal_care'],
  ['hand soap', 'personal_care'],
  ['razors', 'personal_care'],
  ['sunscreen', 'personal_care'],
  ['vitamins', 'personal_care'],

  // ── no guess is the right guess ─────────────────────────────────────────
  ['מתנה לאמא', null],
  ['כרטיס ברכה', null],
  ['עציץ', null],
  ['מטען לטלפון', null],
  ['נעליים', null],
  ['חולצה', null],
  ['לשאול את נופר', null],
  ['פרחים', null],
  ['אוכל לחתול', null],
  ['חול לחתולים', null],

  // ── held out, then kept ─────────────────────────────────────────────────
  // Written as a blind check AFTER the dictionary, and measured before anything
  // was tuned against it: 87.6% on first run, against 72.0% for the engine it
  // replaced. What it caught — construct forms, who an item is for, a phrase
  // outranking the head noun — was fixed properly, and the items stay here so
  // it stays fixed.
  ['פלפל צהוב', 'produce'],
  ['פלפל חריף', 'produce'],
  ['חסה אייסברג', 'produce'],
  ['עגבניות תמר', 'produce'],
  ['גזר גמדי', 'produce'],
  ['ענבים ירוקים', 'produce'],
  ['תפוחי גאלה', 'produce'],
  ['אבוקדו האס', 'produce'],
  ['נענע טרייה', 'produce'],
  ['תפוזי דם', 'produce'],
  ['מלון כתום', 'produce'],
  ['כוסברה טרייה', 'produce'],
  ['אננס חתוך', 'produce'],
  ["תמרים מג'הול", 'produce'],
  ['סברס', 'produce'],
  ['שומר', 'produce'],
  ['שום קלוף', 'produce'],
  ['מלפפונים בייבי', 'produce'],
  ['תפוחי עץ ירוקים', 'produce'],
  ['לימונים ירוקים', 'produce'],
  ['לחם לבן', 'bakery'],
  ['לחם כוסמין', 'bakery'],
  ['לחמניות המבורגר', 'bakery'],
  ['פיתות מקמח מלא', 'bakery'],
  ['בורקס גבינה', 'bakery'],
  ['חלה מתוקה', 'bakery'],
  ['עוגת גבינה', 'bakery'],
  ['קרואסון שוקולד', 'bakery'],
  ['טוסט', 'bakery'],
  ['לחם ללא גלוטן', 'bakery'],
  ['באגט צרפתי', 'bakery'],
  ['מאפה גבינה', 'bakery'],
  ['חלב 1%', 'dairy_eggs'],
  ['חלב דל לקטוז', 'dairy_eggs'],
  ['גבינה צהובה פרוסה', 'dairy_eggs'],
  ['גבינת עיזים', 'dairy_eggs'],
  ['יוגורט דנונה', 'dairy_eggs'],
  ['שמנת 32%', 'dairy_eggs'],
  ['חמאה מלוחה', 'dairy_eggs'],
  ['ביצים חופש', 'dairy_eggs'],
  ['ביצים גודל L', 'dairy_eggs'],
  ['מעדן שוקולד', 'dairy_eggs'],
  ['פודינג וניל', 'dairy_eggs'],
  ["קוטג' 3%", 'dairy_eggs'],
  ['גבינה בולגרית', 'dairy_eggs'],
  ['מוצרלה מגורדת', 'dairy_eggs'],
  ['יוגורט פרי', 'dairy_eggs'],
  ['דני', 'dairy_eggs'],
  ['אקטימל', 'dairy_eggs'],
  ['שוקו בשקית', 'dairy_eggs'],
  ['חזה עוף פרוס', 'meat_fish'],
  ['שניצל עוף', 'meat_fish'],
  ['בשר טחון בקר', 'meat_fish'],
  ['קציצות בקר', 'meat_fish'],
  ['נקניקיות עוף', 'meat_fish'],
  ['פילה אמנון', 'meat_fish'],
  ['דג לברק', 'meat_fish'],
  ['סלמון מעושן', 'meat_fish'],
  ['צלעות כבש', 'meat_fish'],
  ['פרגית בלי עור', 'meat_fish'],
  ['המבורגר ביתי', 'meat_fish'],
  ['כבד בקר', 'meat_fish'],
  ['שווארמה הודו', 'meat_fish'],
  ['פסטרמה הודו', 'meat_fish'],
  ['נתחי פרגית', 'meat_fish'],
  ['שוקי עוף', 'meat_fish'],
  ['אורז פרסי', 'pantry'],
  ['פסטה פנה', 'pantry'],
  ['ספגטי מלא', 'pantry'],
  ['קמח לבן', 'pantry'],
  ['סוכר לבן', 'pantry'],
  ['חומוס בקופסה', 'pantry'],
  ['רוטב פסטה', 'pantry'],
  ['קטשופ היינץ', 'pantry'],
  ['מיונז הלמנס', 'pantry'],
  ["חרדל דיז'ון", 'pantry'],
  ['תבלין שווארמה', 'pantry'],
  ['פפריקה מתוקה', 'pantry'],
  ['כמון טחון', 'pantry'],
  ['פתיתים אפויים', 'pantry'],
  ['עדשים שחורות', 'pantry'],
  ['שעועית בקופסה', 'pantry'],
  ['תירס מתוק', 'pantry'],
  ['טונה בשמן', 'pantry'],
  ['זיתי קלמטה', 'pantry'],
  ['ממרח תמרים', 'pantry'],
  ['דבש טבעי', 'pantry'],
  ['ריבת תות', 'pantry'],
  ['קפה שחור', 'pantry'],
  ['קפה אספרסו', 'pantry'],
  ['תה נענע', 'pantry'],
  ['שיבולת שועל דקה', 'pantry'],
  ['דגני בוקר לילדים', 'pantry'],
  ['אגוזי קשיו', 'pantry'],
  ['צימוקים שחורים', 'pantry'],
  ["רוטב צ'ילי מתוק", 'pantry'],
  ['סויה', 'pantry'],
  ['אורז סושי', 'pantry'],
  ['אצות נורי', 'pantry'],
  ['חלב מרוכז', 'pantry'],
  ['שמרים יבשים', 'pantry'],
  ["גלידה בן אנד ג'ריס", 'frozen'],
  ['ארטיק שוקולד', 'frozen'],
  ['פיצה משפחתית', 'frozen'],
  ['אפונה וגזר קפואים', 'frozen'],
  ['שעועית קפואה', 'frozen'],
  ['מלאווח קפוא', 'frozen'],
  ['פסטה קפואה', 'frozen'],
  ["בלינצ'ס", 'frozen'],
  ['קובה סלק', 'frozen'],
  ['לביבות תפוחי אדמה', 'frozen'],
  ['פירות יער קפואים', 'frozen'],
  ['גלידה וניל', 'frozen'],
  ['במבה נוגט', 'snacks_sweets'],
  ['ביסלי גריל', 'snacks_sweets'],
  ["צ'יטוס חריף", 'snacks_sweets'],
  ['שוקולד פרה', 'snacks_sweets'],
  ['עוגיות אוראו', 'snacks_sweets'],
  ['חטיף שוקולד', 'snacks_sweets'],
  ['וופלים', 'snacks_sweets'],
  ['סוכריות על מקל', 'snacks_sweets'],
  ['פופקורן למיקרו', 'snacks_sweets'],
  ['חטיפי אנרגיה', 'snacks_sweets'],
  ['שוקולד לבן', 'snacks_sweets'],
  ['בונבוניירה', 'snacks_sweets'],
  ['חטיף בריאות', 'snacks_sweets'],
  ['עוגיות חמאה', 'snacks_sweets'],
  ['מים בבקבוק', 'beverages'],
  ['בקבוק מים גדול', 'beverages'],
  ['קולה זירו', 'beverages'],
  ['ספרייט זירו', 'beverages'],
  ['מיץ תפוחים', 'beverages'],
  ['מיץ תפוזים סחוט', 'beverages'],
  ['פריגת אשכוליות', 'beverages'],
  ['תה קר אפרסק', 'beverages'],
  ['נקטר', 'beverages'],
  ['מים מינרליים', 'beverages'],
  ['שוופס טוניק', 'beverages'],
  ['לימונענע גרוס', 'beverages'],
  ['יין רוזה', 'alcohol'],
  ['יין מתוק', 'alcohol'],
  ['בקבוק יין', 'alcohol'],
  ['שישיית בירה גולדסטאר', 'alcohol'],
  ['וויסקי', 'alcohol'],
  ["ג'ק דניאלס", 'alcohol'],
  ['בקרדי', 'alcohol'],
  ['אבסולוט', 'alcohol'],
  ['ערק עלית', 'alcohol'],
  ['ליקר קפה', 'alcohol'],
  ['בירה קורונה', 'alcohol'],
  ['יין קברנה', 'alcohol'],
  ['חיתולים מידה 4', 'baby'],
  ['מגבונים לתינוק', 'baby'],
  ['מטרנה שלב 2', 'baby'],
  ['בקבוק האכלה', 'baby'],
  ['מוצץ לתינוק', 'baby'],
  ['קרם לתינוק', 'baby'],
  ['שמפו לתינוק', 'baby'],
  ['אבקת תמ"ל', 'baby'],
  ['מחיות לתינוקות', 'baby'],
  ['דייסת סולת', 'baby'],
  ['טיטולים לגדולים', 'baby'],
  ['נוזל לרצפה', 'household'],
  ['אקונומיקה סנו', 'household'],
  ["ג'ל למדיח", 'household'],
  ['קפסולות למדיח', 'household'],
  ['מרכך כביסה בדין', 'household'],
  ['אבקת כביסה אריאל', 'household'],
  ['נייר טואלט לילי', 'household'],
  ['מגבות מטבח', 'household'],
  ['שקיות ניילון', 'household'],
  ['שקית אשפה', 'household'],
  ['ספוגי כלים', 'household'],
  ['מטליות מיקרופייבר', 'household'],
  ['ספריי לניקוי', 'household'],
  ['נרות נשמה', 'household'],
  ['סוללות AA', 'household'],
  ['נורת לד', 'household'],
  ['אבקת ניקוי', 'household'],
  ['מנקה חלונות', 'household'],
  ['מטהר אסלה', 'household'],
  ['בלוק לאסלה', 'household'],
  ['צלחות נייר', 'disposables'],
  ['כוסות פלסטיק', 'disposables'],
  ['סכו"ם פלסטיק', 'disposables'],
  ['מגשי אלומיניום', 'disposables'],
  ['כוסות לקפה', 'disposables'],
  ['מפיות נייר', 'disposables'],
  ['קשיות לשתייה', 'disposables'],
  ['קופסאות פלסטיק', 'disposables'],
  ['תבניות חד פעמיות', 'disposables'],
  ['משחת שיניים קולגייט', 'personal_care'],
  ['מברשת שיניים חשמלית', 'personal_care'],
  ['דאודורנט ספריי', 'personal_care'],
  ['קרם ידיים ניוואה', 'personal_care'],
  ['סבון נוזלי', 'personal_care'],
  ["ג'ל לשיער", 'personal_care'],
  ['תער גילוח', 'personal_care'],
  ["סכיני גילוח ג'ילט", 'personal_care'],
  ['תחבושות אולוויז', 'personal_care'],
  ['אקמול פוקוס', 'personal_care'],
  ['ויטמין C', 'personal_care'],
  ['קרם הגנה לילדים', 'personal_care'],
  ['מסכה לשיער', 'personal_care'],
  ['מי פנים', 'personal_care'],
  ['שמן לגוף', 'personal_care'],
  ["לק ג'ל", 'personal_care'],
  ['פלסטר לפצעים', 'personal_care'],
  ['כרטיס מתנה', null],
  ['ספר', null],
  ['עט', null],
  ['מחברת', null],
  ['צבעים לילדים', null],
  ['בלון', null],
  ['מטריה', null],
  ['כבל USB', null],
  ['גרביים', null],
  ['צעצוע', null],

  // ── second blind set, then kept ─────────────────────────────────────────
  // Written BEFORE the rule changes it measured, and scored once untouched:
  // 97.3%. Its real misses — a plural head noun losing to an exact modifier,
  // a three-letter stem swallowing an unrelated word, two missing words —
  // were fixed as rules rather than as special cases.
  ['חסה לליק', 'produce'],
  ['עגבניות שרי צהובות', 'produce'],
  ['פלפל ירוק', 'produce'],
  ['בצל לבן', 'produce'],
  ['קולורבי סגול', 'produce'],
  ['תפוחי עץ פינק ליידי', 'produce'],
  ['אגסים ספדונה', 'produce'],
  ['ענבים שחורים', 'produce'],
  ['מנגו מאיה', 'produce'],
  ['ליים טרי', 'produce'],
  ['פטרוזיליה טרייה', 'produce'],
  ['שמיר טרי', 'produce'],
  ['בטטה כתומה', 'produce'],
  ['תרד טרי', 'produce'],
  ['דלעת ערמונים', 'produce'],
  ['כרוב סגול', 'produce'],
  ['צנונית אדומה', 'produce'],
  ['סלק אדום', 'produce'],
  ['לחם דגנים', 'bakery'],
  ['חלה עגולה', 'bakery'],
  ['פיתה ביתית', 'bakery'],
  ['לחמניות מתוקות', 'bakery'],
  ['עוגת תפוזים', 'bakery'],
  ['קרואסונים חמאה', 'bakery'],
  ['מאפה שמרים', 'bakery'],
  ['רוגלעך', 'bakery'],
  ['גבינה צפתית 5%', 'dairy_eggs'],
  ['יוגורט טבעי', 'dairy_eggs'],
  ['שמנת מתוקה 38%', 'dairy_eggs'],
  ['חלב עמיד', 'dairy_eggs'],
  ['מעדן וניל', 'dairy_eggs'],
  ['גבינת קממבר', 'dairy_eggs'],
  ['חמאה 82%', 'dairy_eggs'],
  ['ביצים אורגניות', 'dairy_eggs'],
  ['לבן תנובה', 'dairy_eggs'],
  ['משקה חלב', 'dairy_eggs'],
  ['שוקו תנובה', 'dairy_eggs'],
  ['עוף חתוך לשמינית', 'meat_fish'],
  ['חזה עוף בגריל', 'meat_fish'],
  ['פרגיות בגריל', 'meat_fish'],
  ['בשר לגולאש', 'meat_fish'],
  ['אנטריקוט בקר', 'meat_fish'],
  ['צלעות עגל', 'meat_fish'],
  ['נקניק סלמי', 'meat_fish'],
  ['טונה אדומה טרייה', 'meat_fish'],
  ['פילה מוסר ים', 'meat_fish'],
  ['דג סלמון', 'meat_fish'],
  ['קבב טלה', 'meat_fish'],
  ['שניצל הודו', 'meat_fish'],
  ['אורז לבן', 'pantry'],
  ['פסטה ספגטי', 'pantry'],
  ['קמח מלא', 'pantry'],
  ['סוכר דמררה', 'pantry'],
  ['מלח ים', 'pantry'],
  ['שמן חמניות', 'pantry'],
  ['רוטב עגבניות ביתי', 'pantry'],
  ['חומוס מבושל', 'pantry'],
  ['גרגרי חומוס יבשים', 'pantry'],
  ['טחינה ירושלמית', 'pantry'],
  ['קפה נמס עלית', 'pantry'],
  ['תה ויסוצקי', 'pantry'],
  ['דגני בוקר כוכבים', 'pantry'],
  ['ריבת חלב', 'pantry'],
  ['קטשופ אסם', 'pantry'],
  ['פתיתים אסם', 'pantry'],
  ['מרק בצל אינסטנט', 'pantry'],
  ['אבקת מרק עוף', 'pantry'],
  ['שקדי מרק אסם', 'pantry'],
  ['פלפל שחור גרוס', 'pantry'],
  ['קינמון טחון', 'pantry'],
  ['שעועית אדומה בקופסה', 'pantry'],
  ['חומץ לבן', 'pantry'],
  ['גלידה שוקולד', 'frozen'],
  ['ארטיקים לילדים', 'frozen'],
  ['בורקס גבינה קפוא', 'frozen'],
  ['שניצל תירס קפוא', 'frozen'],
  ['ירקות מוקפצים קפואים', 'frozen'],
  ["צ'יפס תנור קפוא", 'frozen'],
  ['אפונה ירוקה קפואה', 'frozen'],
  ['גלידת מגנום', 'frozen'],
  ['במבה מתוקה', 'snacks_sweets'],
  ['ביסלי בצל', 'snacks_sweets'],
  ['שוקולד מריר', 'snacks_sweets'],
  ['מקופלת חלב', 'snacks_sweets'],
  ['חטיף תמרים', 'snacks_sweets'],
  ['עוגיות שיבולת שועל', 'snacks_sweets'],
  ['וופל שוקולד', 'snacks_sweets'],
  ['פיצוחים מעורבים', 'snacks_sweets'],
  ['גרעינים שחורים', 'snacks_sweets'],
  ['סוכריות מנטה', 'snacks_sweets'],
  ['קליק קורנפלקס', 'snacks_sweets'],
  ['מים מינרליים נביעות', 'beverages'],
  ['בקבוק סודה', 'beverages'],
  ['קוקה קולה 1.5 ליטר', 'beverages'],
  ['מיץ ענבים אדומים', 'beverages'],
  ['פריגת תפוזים', 'beverages'],
  ['תה קר לימון', 'beverages'],
  ['לימונדה ביתית', 'beverages'],
  ['משקה אנרגיה XL', 'beverages'],
  ['מי עדן 6 בקבוקים', 'beverages'],
  ['יין לבן יבש', 'alcohol'],
  ['בירה שישייה', 'alcohol'],
  ['וודקה אבסולוט', 'alcohol'],
  ['ערק אשקלון', 'alcohol'],
  ['יין ירדן', 'alcohol'],
  ['שמפניה מוט', 'alcohol'],
  ['חיתולים האגיס מידה 5', 'baby'],
  ['מגבונים לחים לתינוק', 'baby'],
  ['סימילאק שלב 3', 'baby'],
  ['מחית תפוחים לתינוק', 'baby'],
  ['מוצץ סיליקון', 'baby'],
  ["אקונומיקה ג'ל", 'household'],
  ['נוזל רצפות מבריק', 'household'],
  ['שקיות אשפה גדולות', 'household'],
  ['נייר טואלט משולש', 'household'],
  ['מגבות נייר סופגות', 'household'],
  ['מרכך כביסה מרוכז', 'household'],
  ['טבליות מדיח פיניש', 'household'],
  ['ספוגי ניקוי', 'household'],
  ['מטליות לחות', 'household'],
  ['שקיות זבל עם שרוך', 'household'],
  ['נייר אלומיניום', 'household'],
  ['נרות חנוכה', 'household'],
  ['צלחות קרטון', 'disposables'],
  ['כוסות קרטון', 'disposables'],
  ['מזלגות פלסטיק', 'disposables'],
  ['מפיות צבעוניות', 'disposables'],
  ['קשיות נייר', 'disposables'],
  ['כפיות פלסטיק', 'disposables'],
  ['שמפו נגד קשקשים', 'personal_care'],
  ['מרכך שיער לשיער יבש', 'personal_care'],
  ['סבון פנים', 'personal_care'],
  ['משחת שיניים לבנה', 'personal_care'],
  ['דאודורנט רול און', 'personal_care'],
  ['קרם לחות לפנים', 'personal_care'],
  ['סכין גילוח', 'personal_care'],
  ['תחבושות לילה', 'personal_care'],
  ['ויטמין D3', 'personal_care'],
  ['אקמול לילדים', 'personal_care'],
  ['מסיר איפור', 'personal_care'],
  ['קרם הגנה SPF 50', 'personal_care'],
  ['כרטיס לסרט', null],
  ['פלאפון', null],
  ['מתנה ליום הולדת', null],
  ['ספרים לבית ספר', null],
  ['קישוטים', null],
  ['מדבקות', null],
];
